### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by Qhan-Hu** [meteorlium/1DBloodFlowPINNs-pelvic-pytorch#1]
您好，最近基于您的代码研究PINN，非常感谢您这份利用pytorch编写的代码。但是在学习您的代码的时候，有两个小问题一直困扰着我，希望您能有空帮我解答一下。
1. 在utility.py的第79和第82行，关于血管上界的定义似乎是错误的。根据您的写法，这两根血管具有相同的上界，但是这又无法确保measurement_points是存在于每根血管中点的，而且根据论文中给出的physiological data，这两根血管的上界也应该是不同的。
2. 在train.py的第88行，您定义了三组分叉[3,6,2]，[6,7,5]，[2,1,4]，然而该顺序与utility.py的第105行定义的三个交叉点的顺序不一致。
但是针对上述问题进行代码修改后，神经网络的计算结果变得很差。因此，关于这两个问题我感到十分困惑，希望能够得到您的帮助，不胜感激！

**Comment by meteorlium** [comment]
你好，我认为你提出的问题来源于代码的血管序号和论文中的图片序号不一致。我在readme里更新了血管序号图，应该可以解决你的问题。

**Comment by Qhan-Hu** [comment]
您好，抱歉再次打扰您，非常感谢您的更新。但是这似乎仍然无法解答第二个问题，因为utility.py的第105行定义的三个交叉点的顺序是[3, 2, 6]三根血管，而在train.py的第88行的三组分叉[**3**,6,2]，[**6**,7,5]，[**2**,1,4]与bif_point是矛盾的。

**Comment by meteorlium** [comment]
第二个问题你说的没错，确实是序号有错误。我把utility.py中的交叉点顺序改成和train中一致，重新训练了一次，result_loss和pressure, velocity看起来还行，和之前差不多？你可以看一下我更新后的结果符不符合你的预期。

**Comment by Qhan-Hu** [comment]
很抱歉没有及时反馈给您，您的修改非常有帮助，是符合预期的结果。非常感谢您的帮助！
